# Generated by Django 3.2.16 on 2023-01-23 12:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='last_message_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 23, 12, 59, 35, 739686), verbose_name='Last message date'),
        ),
        migrations.AlterField(
            model_name='conversationmessages',
            name='message_contents',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1, 'A message cannot be blank.'), django.core.validators.MaxLengthValidator(1000)], verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='conversation_thumbnail',
            field=models.ImageField(upload_to='', verbose_name='Conversation Image'),
        ),
    ]
