# Generated by Django 3.2.16 on 2023-01-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_alter_conversations_last_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='conversation_title',
        ),
    ]
