# Generated by Django 4.1.3 on 2022-11-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(default='Cruiser', max_length=30, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='listings',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='listing_status',
            field=models.CharField(choices=[('A', 'Available'), ('P', 'Pending Sale'), ('S', 'Sold'), ('N', 'Not Listed')], max_length=1, verbose_name='Listing Status'),
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listings')),
            ],
        ),
    ]
