# Generated by Django 4.1.3 on 2022-11-30 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listings_category_listings_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
        migrations.AddField(
            model_name='listings',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=30, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='listings',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='listings',
            name='boat_feature_list',
            field=models.CharField(blank=True, default='', max_length=7000),
        ),
        migrations.AlterField(
            model_name='listings',
            name='cabin_headroom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Cabin Headroom'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='number_of_engines',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Number of main engines or motors'),
        ),
    ]
