# Generated by Django 4.1.3 on 2022-12-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listingmedia_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='featured_image',
            field=models.ImageField(default='default_image.png', upload_to='', verbose_name='Featured Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='listing_status',
            field=models.CharField(choices=[('A', 'Available'), ('P', 'Pending Sale'), ('S', 'Sold'), ('N', 'Not Listed')], default='A', max_length=1, verbose_name='Listing Status'),
        ),
    ]
