# Generated by Django 3.2.16 on 2023-01-02 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listings_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='range',
        ),
        migrations.AddField(
            model_name='listings',
            name='total_hp',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='Total HP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='boat_feature_list',
            field=models.CharField(blank=True, default='', max_length=3500),
        ),
        migrations.AlterField(
            model_name='listings',
            name='listing_description',
            field=models.TextField(blank=True, max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='listings',
            name='type',
            field=models.CharField(choices=[('P', 'Power'), ('S', 'Sail')], default='P', max_length=1, verbose_name='Type'),
        ),
    ]
