# Generated by Django 3.2.16 on 2023-01-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20230102_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='country',
            field=models.CharField(choices=[('BE', 'Belgium'), ('CA', 'Canada'), ('DE', 'Denmark'), ('FI', 'Finland'), ('FR', 'France'), ('GE', 'Germany'), ('GI', 'Gibraltar'), ('GE', 'Greece'), ('IR', 'Republic of Ireland'), ('IT', 'Italy'), ('MA', 'Malta'), ('NE', 'Netherlands'), ('NO', 'Norway'), ('PO', 'Poland'), ('PR', 'Portugal'), ('ES', 'Spain'), ('SV', 'Sweden'), ('TK', 'Turkey'), ('UK', 'United Kingdom'), ('US', 'United States')], default='UK', max_length=2, verbose_name='Country'),
        ),
    ]
