# Generated by Django 3.2.16 on 2023-01-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listings_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='cabin_headroom',
        ),
    ]
