# Generated by Django 3.2.16 on 2023-01-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_listings_cabin_headroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='hull_configuration',
            field=models.CharField(choices=[('M', 'Monohull'), ('C', 'Catamaran'), ('T', 'Trimaran')], default='M', max_length=1, verbose_name='Hull Configuration'),
        ),
        migrations.AlterField(
            model_name='listingmedia',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('PC', 'Planing Cruiser'), ('DC', 'Displacement Cruiser'), ('S', 'Sport'), ('F', 'Fishing'), ('RT', 'RIB/Tender'), ('NC', 'Narrow/Canal'), ('C', 'Cruiser'), ('DS', 'Day Sailer'), ('DI', 'Dinghy'), ('RA', 'Racing')], default='PC', max_length=4, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='U', max_length=1, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='hull_material',
            field=models.CharField(choices=[('F', 'Fibreglass/GRP'), ('S', 'Steel'), ('W', 'Wood'), ('A', 'Aluminium'), ('O', 'Other')], max_length=1, verbose_name='Hull Material'),
        ),
    ]
