# Generated by Django 3.2.16 on 2023-01-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20230109_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='featured_image_thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Featured Image Thumnail'),
        ),
    ]
