# Generated by Django 3.2.16 on 2023-01-21 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listings_featured_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='cruising_speed',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Cruising Speed'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='draft',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)], verbose_name='Draft'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='listing_description',
            field=models.TextField(max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='listings',
            name='maximum_speed',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Maximum Speed'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(400)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='total_hp',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)], verbose_name='Total HP'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(500000)], verbose_name='Weight'),
        ),
    ]
