# Generated by Django 3.2.16 on 2023-01-24 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20230121_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='total_hp',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)], verbose_name='Total HP'),
        ),
    ]
